name: 'Smart csproj Version Grabber'
description: 'Smartly finds .sln or .csproj files and extracts version for CI/CD workflows.'
author: 'Raycynix'

branding:
  icon: 'package'
  color: 'gray-dark'

inputs:
  path:
    description: 'Manual path to .csproj file. If not provided, searches in .sln or root.'
    required: false
    default: ''

outputs:
  version:
    description: 'The version extracted from the project file.'
  project_path:
    description: 'The actual path to the .csproj file used.'

runs:
  using: 'node24'
  main: 'dist/index.js'
