name: 'Smart csproj Version Grabber'
description: 'Finds a .NET project and extracts its version from .csproj or Directory.Build.props.'
author: 'Raycynix'

branding:
  icon: 'package'
  color: 'gray-dark'

inputs:
  path:
    description: 'Manual path to .csproj file. If not provided, searches in .sln or root.'
    required: false
    default: ''

outputs:
  version:
    description: 'The version extracted from the project or its nearest Directory.Build.props file.'
  project_path:
    description: 'The path to the selected .csproj file.'

runs:
  using: 'node24'
  main: 'dist/index.js'
